//! `mariadbd` child-process management.
//!
//! Responsibilities:
//! - First-run init (`mariadb-install-db` to create the system tables).
//! - Spawn `mariadbd` on `127.0.0.1:<port>` with our datadir / socket / pid.
//! - Poll the TCP port until accepting connections.
//! - Ensure the `ub` database and `ub_local` user exist on every boot
//!   (idempotent — uses `CREATE … IF NOT EXISTS` / `CREATE USER IF NOT
//!   EXISTS`). Required because the per-install password is generated by the
//!   shell, not bootstrapped by Flyway.
//! - On shutdown, prefer `mysqladmin shutdown` (clean) before falling back
//!   to `SIGTERM` then `SIGKILL`.

#[cfg(unix)]
use std::env;
use std::io;
use std::net::TcpStream;
use std::process::{Child, Command, Stdio};
use std::time::{Duration, Instant};

#[cfg(windows)]
use std::os::windows::process::CommandExt;

use crate::supervisor::{ChildProcess, MariadbConfig};

/// Windows: mariadbd.exe / mariadb.exe / mariadb-install-db.exe are
/// console-subsystem binaries. Spawning them from the GUI shell (which has no
/// console to inherit) would pop a blank console window for each child, so
/// request no window via `CREATE_NO_WINDOW`.
#[cfg(windows)]
fn hide_console_window(cmd: &mut Command) {
    cmd.creation_flags(0x0800_0000); // CREATE_NO_WINDOW
}

#[cfg(not(windows))]
fn hide_console_window(_cmd: &mut Command) {}

const READY_TIMEOUT: Duration = Duration::from_secs(120);
const POLL_INTERVAL: Duration = Duration::from_millis(250);
const SHUTDOWN_TIMEOUT: Duration = Duration::from_secs(20);

fn mariadb_command(cfg: &MariadbConfig, name: &str) -> Command {
    #[cfg_attr(windows, allow(unused_mut))]
    let mut cmd = Command::new(cfg.bin_dir.join(crate::bundle::exe_name(name)));
    hide_console_window(&mut cmd);
    // Windows loads DLLs from the exe's own directory, so only unix needs a
    // loader path pointing at the bundled `lib/`.
    #[cfg(unix)]
    if let Some(lib) = &cfg.lib_dir {
        #[cfg(target_os = "macos")]
        {
            let path = env::var("DYLD_LIBRARY_PATH").unwrap_or_default();
            let combined = if path.is_empty() {
                lib.display().to_string()
            } else {
                format!("{}:{}", lib.display(), path)
            };
            cmd.env("DYLD_LIBRARY_PATH", combined);
        }
        #[cfg(not(target_os = "macos"))]
        {
            let path = env::var("LD_LIBRARY_PATH").unwrap_or_default();
            let combined = if path.is_empty() {
                lib.display().to_string()
            } else {
                format!("{}:{}", lib.display(), path)
            };
            cmd.env("LD_LIBRARY_PATH", combined);
        }
    }
    cmd
}

pub fn start(cfg: &MariadbConfig) -> io::Result<ChildProcess> {
    if cfg.external {
        log::info!(
            "APP_DESKTOP_SKIP_MARIADB=1 — attaching to external mariadbd on \
             127.0.0.1:{}",
            cfg.port
        );
        if !port_open(cfg.port) {
            return Err(io::Error::new(
                io::ErrorKind::ConnectionRefused,
                format!(
                    "APP_DESKTOP_SKIP_MARIADB=1 but no mariadbd is listening \
                     on 127.0.0.1:{}",
                    cfg.port
                ),
            ));
        }
        // Hand back a dummy child so the lifecycle code is uniform. The
        // shutdown path special-cases `external` and never touches it.
        return Ok(ChildProcess::new("mariadb (external)", dummy_child()?));
    }

    // First-run: initialise the system tables.
    if !cfg.datadir.exists() {
        log::info!(
            "Initialising MariaDB datadir at {}",
            cfg.datadir.display()
        );
        std::fs::create_dir_all(&cfg.datadir)?;
        let mut install = mariadb_command(cfg, "mariadb-install-db");
        install.arg(format!("--datadir={}", cfg.datadir.display()));
        // `--auth-root-authentication-method=normal` only exists in the unix
        // shell-script variant. The Windows `mariadb-install-db.exe` already
        // creates a passwordless root@localhost by default.
        #[cfg(not(windows))]
        install.arg("--auth-root-authentication-method=normal");
        let status = install
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status()
            .map_err(|e| {
                io::Error::new(
                    e.kind(),
                    format!("mariadb-install-db failed to spawn: {e}"),
                )
            })?;
        if !status.success() {
            return Err(io::Error::new(
                io::ErrorKind::Other,
                format!(
                    "mariadb-install-db exited with {status:?}; see {}",
                    cfg.log_file.display()
                ),
            ));
        }
    }

    if port_open(cfg.port) {
        // Either a stale daemon or the user is on `cargo run` for the
        // second time without quitting properly. Fail loudly rather than
        // silently fighting them.
        return Err(io::Error::new(
            io::ErrorKind::AddrInUse,
            format!(
                "127.0.0.1:{} already in use. Stop the other mariadbd \
                 (e.g. `pkill -f mariadbd`) or set APP_DESKTOP_SKIP_MARIADB=1.",
                cfg.port
            ),
        ));
    }

    log::info!(
        "Starting mariadbd on 127.0.0.1:{} (datadir={})",
        cfg.port,
        cfg.datadir.display()
    );
    let mut daemon = mariadb_command(cfg, "mariadbd");
    daemon
        .arg(format!("--datadir={}", cfg.datadir.display()))
        .arg(format!("--port={}", cfg.port))
        .arg("--bind-address=127.0.0.1")
        .arg(format!("--pid-file={}", cfg.pid_file.display()))
        .arg(format!("--log-error={}", cfg.log_file.display()));
    // Unix sockets don't exist on Windows (`--socket` there means a named
    // pipe); the admin channel uses TCP instead — see `admin_conn_args`.
    #[cfg(not(windows))]
    daemon.arg(format!("--socket={}", cfg.socket.display()));
    let child = daemon
        // Quieter startup — the user only sees mariadbd output if something
        // catches fire, in which case the log file has full detail.
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .map_err(|e| {
            io::Error::new(
                e.kind(),
                format!(
                    "spawn mariadbd ({}) failed: {e}",
                    cfg.bin_dir.join(crate::bundle::exe_name("mariadbd")).display()
                ),
            )
        })?;

    let pid = child.id();
    log::info!("mariadbd pid={pid}; polling for readiness…");
    wait_until_ready(cfg.port, READY_TIMEOUT)?;
    log::info!("mariadbd ready.");

    ensure_schema(cfg)?;
    Ok(ChildProcess::new("mariadbd", child))
}

/// Connection args for the root admin channel: unix socket on unix (0600
/// inside APP_DATA), TCP loopback on Windows (no unix sockets there; root is
/// passwordless for localhost on a fresh datadir either way).
fn admin_conn_args(cfg: &MariadbConfig) -> Vec<String> {
    #[cfg(windows)]
    {
        vec![
            "--host=127.0.0.1".to_string(),
            format!("--port={}", cfg.port),
        ]
    }
    #[cfg(not(windows))]
    {
        vec![format!("--socket={}", cfg.socket.display())]
    }
}

/// Bring the `ub` database + `ub_local` user up to spec. Safe to re-run.
fn ensure_schema(cfg: &MariadbConfig) -> io::Result<()> {
    // Connect via socket as root (no password — `mariadb-install-db
    // --auth-root-authentication-method=normal` leaves root passwordless for
    // local socket access, which is fine since the socket lives inside
    // APP_DATA with 0600 permissions).
    let bootstrap = format!(
        "CREATE DATABASE IF NOT EXISTS ub CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\n\
         CREATE USER IF NOT EXISTS '{user}'@'127.0.0.1' IDENTIFIED BY '{pw}';\n\
         ALTER USER '{user}'@'127.0.0.1' IDENTIFIED BY '{pw}';\n\
         GRANT ALL PRIVILEGES ON ub.* TO '{user}'@'127.0.0.1';\n\
         FLUSH PRIVILEGES;\n",
        user = cfg.user,
        pw = cfg.password.replace('\'', "''"),
    );

    let output = mariadb_command(cfg, "mariadb")
        .args(admin_conn_args(cfg))
        .arg("-u")
        .arg("root")
        .arg("-e")
        .arg(&bootstrap)
        .output()
        .map_err(|e| {
            io::Error::new(e.kind(), format!("mariadb client spawn failed: {e}"))
        })?;
    if !output.status.success() {
        return Err(io::Error::new(
            io::ErrorKind::Other,
            format!(
                "schema bootstrap failed (exit {:?}): {}",
                output.status,
                String::from_utf8_lossy(&output.stderr)
            ),
        ));
    }
    log::info!("ub database + {} user verified.", cfg.user);
    Ok(())
}

pub fn shutdown(proc: &ChildProcess, cfg: &MariadbConfig) {
    if cfg.external {
        log::info!("External mariadbd — leaving running.");
        return;
    }

    log::info!("Stopping {} (pid {})…", proc.label, proc.pid());

    // Prefer a clean shutdown via the admin command.
    let clean_result = mariadb_command(cfg, "mariadb-admin")
        .args(admin_conn_args(cfg))
        .arg("-u")
        .arg("root")
        .arg("shutdown")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status();

    match clean_result {
        Ok(status) if status.success() => {
            // Wait for the process to exit on its own — usually < 2 s.
            if let Ok(mut guard) = proc.child.lock() {
                let _ = wait_with_timeout(&mut guard, SHUTDOWN_TIMEOUT);
            }
        }
        other => {
            log::warn!("mariadb-admin shutdown failed ({other:?}); falling back to SIGTERM.");
            if let Ok(mut guard) = proc.child.lock() {
                let _ = sigterm(&mut guard);
                let _ = wait_with_timeout(&mut guard, SHUTDOWN_TIMEOUT);
            }
        }
    }
}

fn wait_until_ready(port: u16, timeout: Duration) -> io::Result<()> {
    let deadline = Instant::now() + timeout;
    while Instant::now() < deadline {
        if port_open(port) {
            // Give it a brief grace period for the handshake to settle.
            std::thread::sleep(Duration::from_millis(300));
            return Ok(());
        }
        std::thread::sleep(POLL_INTERVAL);
    }
    Err(io::Error::new(
        io::ErrorKind::TimedOut,
        format!("mariadbd never started accepting connections on 127.0.0.1:{port}"),
    ))
}

fn port_open(port: u16) -> bool {
    let addr = format!("127.0.0.1:{port}");
    TcpStream::connect_timeout(
        &addr.parse().expect("port literal parses"),
        Duration::from_millis(400),
    )
    .is_ok()
}

#[cfg(unix)]
fn sigterm(child: &mut Child) -> io::Result<()> {
    let pid = child.id() as libc::pid_t;
    // SAFETY: kill() with a valid pid + SIGTERM is well-defined; failure
    // returns -1 and sets errno but doesn't UB.
    let rc = unsafe { libc::kill(pid, libc::SIGTERM) };
    if rc == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

#[cfg(not(unix))]
fn sigterm(child: &mut Child) -> io::Result<()> {
    // No SIGTERM on Windows — this path only runs when `mariadb-admin
    // shutdown` already failed, so TerminateProcess is the last resort.
    child.kill()
}

fn wait_with_timeout(child: &mut Child, timeout: Duration) -> io::Result<()> {
    let deadline = Instant::now() + timeout;
    loop {
        match child.try_wait()? {
            Some(_) => return Ok(()),
            None => {
                if Instant::now() >= deadline {
                    log::warn!(
                        "Timeout waiting for pid {} to exit; sending SIGKILL.",
                        child.id()
                    );
                    let _ = child.kill();
                    return child.wait().map(|_| ());
                }
                std::thread::sleep(Duration::from_millis(200));
            }
        }
    }
}

/// Returns a zero-effect `Child` so the `external` code path can hand back a
/// `ChildProcess` without holding `Option<Child>` everywhere. The lifecycle
/// code never blocks on this child — `shutdown` short-circuits on
/// `cfg.external`.
fn dummy_child() -> io::Result<Child> {
    // A command that exits immediately with status 0. Reaping it once is
    // harmless.
    #[cfg(windows)]
    let mut cmd = {
        let mut c = Command::new("cmd");
        c.creation_flags(0x0800_0000); // CREATE_NO_WINDOW — no flash of a console
        c.args(["/C", "exit", "0"]);
        c
    };
    #[cfg(not(windows))]
    let mut cmd = Command::new("true");
    cmd.stdout(Stdio::null()).stderr(Stdio::null()).spawn()
}
